---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: myjenkins-slave-role
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["statefulsets"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["daemonsets"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create","delete","get","list","patch","update","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: myjenkins-slave-rb
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: myjenkins-slave-role
subjects:
- kind: ServiceAccount
  name: myjenkins-slave
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: myjenkins-slave-clusterrole
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["create","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["storgeclasses"]
  verbs: ["create","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["clusterrole"]
  verbs: ["create","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["clusterrolebinding"]
  verbs: ["create","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create","get","list","patch","update","watch"]

---
# Allows myjenkins-slave to create persistent volumes
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myjenkins-slave-crb
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: myjenkins-slave
roleRef:
  kind: ClusterRole
  name: cluster-admin 
  apiGroup: rbac.authorization.k8s.io
---
